SET(LIBRARY_NAME eigen)
SET(LIBRARY_NAME_UPPER EIGEN)
SET(LIBRARY_VERSION eigen-3.3.4)

MESSAGE(${PATH_3RDPARTY}/${LIBRARY_VERSION})
INCLUDE_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/include)
INCLUDE_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/include/eigen3)
