SET(LIBRARY_NAME toolbox)
SET(LIBRARY_NAME_UPPER TOOLBOX)
SET(LIBRARY_VERSION toolbox)

MESSAGE(${PATH_3RDPARTY}/${LIBRARY_VERSION})
INCLUDE_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/include)
INCLUDE_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/include/toolbox)
LINK_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/lib)
SET(${LIBRARY_NAME_UPPER}_LIBS czlt_ocv_extra czlt_shape czlt_utils czht_tracker)
