SET(LIBRARY_NAME cuda)
SET(LIBRARY_NAME_UPPER CUDA)
SET(LIBRARY_VERSION cuda-8.0)

#MESSAGE(${PATH_3RDPARTY}/${LIBRARY_VERSION})
MESSAGE("Get From System")
INCLUDE_DIRECTORIES(/usr/local/cuda-8.0/include)
LINK_DIRECTORIES(/usr/local/cuda-8.0/lib64)
SET(${LIBRARY_NAME_UPPER}_LIBS cublas cudart cudnn)
