SET(LIBRARY_NAME ffmpeg)
SET(LIBRARY_NAME_UPPER FFMPEG)
SET(LIBRARY_VERSION ffmpeg)

MESSAGE(${PATH_3RDPARTY}/${LIBRARY_VERSION})
INCLUDE_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/include)
LINK_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/lib)
SET(${LIBRARY_NAME_UPPER}_LIBS avcodec avdevice avfilter avformat avutil swresample swscale)
