SET(LIBRARY_NAME glog)
SET(LIBRARY_NAME_UPPER GLOG)
SET(LIBRARY_VERSION glog-0.3.5)

MESSAGE(${PATH_3RDPARTY}/${LIBRARY_VERSION})
INCLUDE_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/include)
LINK_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/lib)
SET(${LIBRARY_NAME_UPPER}_LIBS glog)
