SET(LIBRARY_NAME gtest)
SET(LIBRARY_NAME_UPPER GTEST)
SET(LIBRARY_VERSION gtest)

MESSAGE(${PATH_3RDPARTY}/${LIBRARY_VERSION})
INCLUDE_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/include)
LINK_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/lib)
SET(${LIBRARY_NAME_UPPER}_LIBS gtest gtest_main)
