SET(LIBRARY_NAME protobuf)
SET(LIBRARY_NAME_UPPER PROTOBUF)
SET(LIBRARY_VERSION protobuf-3.4.0)

MESSAGE(${PATH_3RDPARTY}/${LIBRARY_VERSION})
INCLUDE_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/include)
LINK_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/lib)
SET(${LIBRARY_NAME_UPPER}_LIBS protobuf protobuf-lite protoc)
