SET(LIBRARY_NAME czml)
SET(LIBRARY_NAME_UPPER CZML)
SET(LIBRARY_VERSION czml)

MESSAGE(${PATH_3RDPARTY}/${LIBRARY_VERSION})
INCLUDE_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/include)
LINK_DIRECTORIES(${PATH_3RDPARTY}/${LIBRARY_VERSION}/lib)
SET(${LIBRARY_NAME_UPPER}_LIBS cz_ml_classifiers cz_ml_detectors cz_ml_utils)
